// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat, faker } from "@snaplet/copycat"
import { defineConfig } from "snaplet"
copycat.setHashKey("rR52S9OdPTxy+EIi")
export default defineConfig({
  generate: {
    async run(snaplet) {
      await snaplet.recipes([
        {
          name: "Spaghetti Bolognese",
          description: "Classic Italian pasta dish with a rich meat sauce.",
          content: "Cook pasta and top it with the delicious Bolognese sauce.",
          cooking_time: Math.floor(Math.random() * 56) + 5
        },
        {
          name: "Chicken Alfredo",
          description: "Creamy pasta dish with grilled chicken and Alfredo sauce.",
          content: "Grill chicken, prepare Alfredo sauce, and toss it with cooked pasta.",
          cooking_time: Math.floor(Math.random() * 56) + 5
        },
        {
          name: "Vegetarian Stir-Fry",
          description: "Healthy stir-fry loaded with colorful vegetables.",
          content: "Chop and stir-fry your favorite vegetables with soy sauce and spices.",
          cooking_time: Math.floor(Math.random() * 56) + 5
        }
      ])

      await snaplet.users(x => x * 3)
    }
  }
})
